version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]

  redis:
    image: redis:7
    command: redis-server --save ""
    ports: ["6379:6379"]

  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=kinesis,kinesisvideo,s3
    ports: ["4566:4566"]
    volumes:
      - ./infra/localstack/init.sh:/etc/localstack/init/ready.d/init.sh:ro

  backend:
    build: ./backend
    env_file: .env
    ports: ["4000:4000"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on: [mongo, redis, localstack]

  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    volumes:
    - ./frontend:/app
    - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: [backend]
